/// <reference types="next/image-types/global" />

/**
 * Image module declarations, committed.
 *
 * Next writes the same reference into `next-env.d.ts`, but that file is
 * generated by `next build` and gitignored, so it exists on a machine that has
 * built the app and nowhere else. `npm run typecheck` runs `tsc` directly and
 * has no build ahead of it, so on a fresh checkout every `import wordmark from
 * "@/assets/…png"` failed with TS2307 — while passing locally and on Railway,
 * where a real build regenerates the file first.
 *
 * A committed declaration makes the typecheck stand on its own.
 */
